name: EVCC Optimizer Proxy
description: HTTP Proxy für EVCC Optimizer mit Request-Modifikation. Setzt charge_from_grid und export_to_grid automatisch auf true.
version: 1.0.14
slug: evcc-optimizer-proxy
image: ghcr.io/achims311/evcc-optimizer-proxy-{arch}
arch:
  - aarch64
  - amd64
startup: services
boot: auto
ports:
  8080/tcp: 8080
hassio_api: true
homeassistant_api: true
options:
  target_url: "https://optimizer.evcc.io"
  use_system_proxy: true
  log_level: "INFO"
schema:
  target_url: str
  proxy_url: str?
  proxy_username: str?
  use_system_proxy: bool
  log_level: list(INFO|DEBUG|WARNING|ERROR)?
environment:
  TZ: UTC
privileged: []
webui: http://[HOST]:[PORT:8080]
