name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4.1.7
    
    - name: Create Release
      uses: softprops/action-gh-release@v2.0.8
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
